version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10.x
    pre_build:
        commands:
            - cd src/frontend
            - npm i
    build:
        commands:
            - npm run build
artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: 'src/frontend/build'